# ----------------------------------------------------- 
# Autostart
# ----------------------------------------------------- 
exec-once = /home/dhili/.config/hypr/start-waybar.sh
exec-once = hyprpaper & sleep 1 && hyprctl hyprpaper wallpaper ",/home/dhili/Downloads/Watchtower.png"
exec-once = swayidle -w \
    timeout 300 'swaylock -c 000000CC' \
    timeout 600 'systemctl suspend' \
    before-sleep 'swaylock -c 000000CC'
exec-once = dbus-update-activation-environment --systemd GTK_THEME=Dracula XDG_CURRENT_DESKTOP=Hyprland
# exec-once = wezterm
