# ----------------------------------------------------- 
# Device
# ----------------------------------------------------- 
# Increase mouse scroll speed
device {
    name = elan0709:00-04f3:30a0-mouse
    scroll_factor = 1.2
}