preload = /home/dhili/Downloads/Archcode.png
preload = /home/dhili/Downloads/Boruto.png
preload = /home/dhili/Downloads/Blueview.png
preload = /home/dhili/Downloads/Redray.png
preload = /home/dhili/Downloads/Linux.jpg
preload = /home/dhili/Downloads/Watchtower.png
preload = /home/dhili/Downloads/Cloudynight.png
preload = /home/dhili/Downloads/Itachi.png
preload = /home/dhili/Downloads/Snownight.png
preload = /home/dhili/Downloads/Purplenight.png

wallpaper = *,/home/dhili/Downloads/Archcode.png
wallpaper = *1,/home/dhili/Downloads/Archcode.png
wallpaper = *2,/home/dhili/Downloads/Boruto.png
wallpaper = *3,/home/dhili/Downloads/Blueview.png
wallpaper = *4,/home/dhili/Downloads/Redray.png
wallpaper = *5,/home/dhili/Downloads/Linux.jpg
wallpaper = *6,/home/dhili/Downloads/Watchtower.png
wallpaper = *7,/home/dhili/Downloads/Cloudynight.png
wallpaper = *8,/home/dhili/Downloads/Itachi.png
wallpaper = *9,/home/dhili/Downloads/Snownight.png
wallpaper = *10,/home/dhili/Downloads/Purplenight.png