# ----------------------------------------------------- 
# Variables
# ----------------------------------------------------- 
# Set $mod to SUPER (Windows key)
$mod = SUPER
$mainMod = SUPER

# See https://wiki.hyprland.org/Configuring/Monitors/
env = XCURSOR_SIZE,24